var siades = require('./siades.js')

async function procesar() {
	var start = Date.now();
	await siades.tareasMateria(1001)
	await siades.postsMateria(1001)
	console.log("Posts y tareas procesados para 1001")
	await siades.tareasMateria(1002)
	await siades.postsMateria(1002)
	console.log("Posts y tareas procesados para 1002")
	await siades.tareasMateria(1003)
	await siades.postsMateria(1003)
	console.log("Posts y tareas procesados para 1003")
	await siades.tareasMateria(1004)
	await siades.postsMateria(1004)
	console.log("Posts y tareas procesados para 1004")
	await siades.tareasMateria(1005)
	await siades.postsMateria(1005)
	console.log("Posts y tareas procesados para 1005")
	await siades.tareasMateria(1006)
	await siades.postsMateria(1006)
	console.log("Posts y tareas procesados para 1006")
	await siades.tareasMateria(2070)
	await siades.postsMateria(2070)
	console.log("Posts y tareas procesados para 2070")
	await siades.tareasMateria(2051)
	await siades.postsMateria(2051)
	console.log("Posts y tareas procesados para 2051")
	await siades.tareasMateria(2088)
	await siades.postsMateria(2088)
	console.log("Posts y tareas procesados para 2088")
	await siades.tareasMateria(2089)
	await siades.postsMateria(2089)
	console.log("Posts y tareas procesados para 2089")
	await siades.tareasMateria(1007)
	await siades.postsMateria(1007)
	console.log("Posts y tareas procesados para 1007")
	await siades.tareasMateria(1008)
	await siades.postsMateria(1008)
	console.log("Posts y tareas procesados para 1008")
	await siades.tareasMateria(1009)
	await siades.postsMateria(1009)
	console.log("Posts y tareas procesados para 1009")
	await siades.tareasMateria(1010)
	await siades.postsMateria(1010)
	console.log("Posts y tareas procesados para 1010")
	await siades.tareasMateria(1011)
	await siades.postsMateria(1011)
	console.log("Posts y tareas procesados para 1011")
	await siades.tareasMateria(1012)
	await siades.postsMateria(1012)
	console.log("Posts y tareas procesados para 1012")
	await siades.tareasMateria(2071)
	await siades.postsMateria(2071)
	console.log("Posts y tareas procesados para 2071")
	await siades.tareasMateria(2024)
	await siades.postsMateria(2024)
	console.log("Posts y tareas procesados para 2024")
	await siades.tareasMateria(2090)
	await siades.postsMateria(2090)
	console.log("Posts y tareas procesados para 2090")
	await siades.tareasMateria(2091)
	await siades.postsMateria(2091)
	console.log("Posts y tareas procesados para 2091")
	var end = Date.now();
	console.log("Tiempo elapsado: " + millisToMinutesAndSeconds(end - start))
}

function millisToMinutesAndSeconds(millis) {
  var minutes = Math.floor(millis / 60000);
  var seconds = ((millis % 60000) / 1000).toFixed(0);
  return minutes + ":" + (seconds < 10 ? '0' : '') + seconds;
}

procesar()